from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors


def generate_study_report(
    filename,
    user_name,
    total_entries,
    total_hours,
    latest_topic,
    streak,
    ai_insight,
    total_problems=0,
    leetcode_total=0,
    leetcode_easy=0,
    leetcode_medium=0,
    leetcode_hard=0
):
    c = canvas.Canvas(filename, pagesize=A4)

    width, height = A4

    primary = colors.HexColor("#168AAD")
    dark = colors.HexColor("#184E77")
    light = colors.HexColor("#D9ED92")
    soft_bg = colors.HexColor("#F7FFF2")

    # Header
    c.setFillColor(primary)
    c.rect(0, height - 90, width, 90, fill=1, stroke=0)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 45, "Trackify AI")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 65, "Learning Analytics Performance Report")

    y = height - 125

    # Title
    c.setFillColor(dark)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "Student Performance Summary")

    y -= 25
    c.setStrokeColor(primary)
    c.line(50, y, 545, y)

    # Summary box
    y -= 25
    c.setFillColor(soft_bg)
    c.roundRect(45, y - 130, 500, 145, 10, fill=1, stroke=0)

    c.setFillColor(dark)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(65, y, f"Student Name: {user_name}")

    y -= 25
    c.setFont("Helvetica", 12)
    c.drawString(65, y, "Report Type: Weekly Learning Analytics")

    y -= 25
    c.drawString(65, y, f"Total Study Entries: {total_entries}")

    y -= 25
    c.drawString(65, y, f"Total Study Hours: {total_hours}")

    y -= 25
    c.drawString(65, y, f"Latest Topic Studied: {latest_topic}")

    y -= 25
    c.drawString(65, y, f"Current Study Streak: {streak} Days")

    # Coding section
    y -= 45
    c.setFillColor(primary)
    c.roundRect(45, y - 5, 500, 28, 6, fill=1, stroke=0)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(60, y + 4, "Coding Progress")

    y -= 35
    c.setFillColor(dark)
    c.setFont("Helvetica", 12)
    c.drawString(60, y, f"Trackify Coding Problems: {total_problems}")

    y -= 25
    c.drawString(60, y, f"LeetCode Total Solved: {leetcode_total}")

    y -= 25
    c.drawString(
        60,
        y,
        f"Easy: {leetcode_easy}    Medium: {leetcode_medium}    Hard: {leetcode_hard}"
    )

    # Rating
    if total_hours >= 20 and total_problems >= 10:
        rating = "Excellent"
        rating_color = colors.green
    elif total_hours >= 10:
        rating = "Good"
        rating_color = colors.orange
    else:
        rating = "Needs Improvement"
        rating_color = colors.red

    y -= 45
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(rating_color)
    c.drawString(60, y, f"Performance Rating: {rating}")

    # AI Insight
    y -= 45
    c.setFillColor(primary)
    c.roundRect(45, y - 5, 500, 28, 6, fill=1, stroke=0)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(60, y + 4, "AI Study Insight")

    y -= 35
    c.setFillColor(soft_bg)
    c.roundRect(45, y - 105, 500, 120, 10, fill=1, stroke=0)

    c.setFillColor(dark)
    c.setFont("Helvetica", 11)

    text = c.beginText(65, y)
    text.setLeading(15)

    words = ai_insight.replace("\n", " ").split()
    line = ""

    for word in words:
        if len(line + " " + word) < 85:
            line += " " + word
        else:
            text.textLine(line.strip())
            line = word

    if line:
        text.textLine(line.strip())

    c.drawText(text)

    # Footer
    c.setStrokeColor(primary)
    c.line(50, 55, 545, 55)

    c.setFillColor(dark)
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(
        50,
        35,
        "Generated by Trackify AI | Learning Analytics Platform"
    )

    c.save()